declare module 'boring-webcrypto-sha256'
declare module 'sha256'
declare module '@vuelidate/core'
declare module '@vuelidate/validators'
declare module '@vuepic/vue-datepicker'
declare module 'vue-tippy'
declare module 'maska'
declare module '@fortawesome/free-regular-svg-icons'
