declare module 'boring-webcrypto-sha256'
declare module 'sha256'
declare module '@vuelidate/core'
declare module '@vuelidate/validators'
declare module 'vue-tippy'
declare module '@fortawesome/free-regular-svg-icons'
declare module '@kyvg/vue3-notification'
